<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Importar')?></h3></td>
        </tr>
    </table>
</div>
<div class="entry-edit">


	<form id="edit_form" name="edit_form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('importsuperproducts/adminhtml_category'); ?>" >
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getStoreConfig('importsuperproducts_options/import/max_file_size'); ?>">
		
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Importação de Categorias')?></h4>
        </div> 
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Selecione o arquivo com os produtos simples')?><span class="required">*</span></td>
                    <td class="input-ele"><input name="category" type="file"></td>
                </tr>
            </table>
        <input type="submit" name="submit" value="Importar">
        </fieldset>
	</form>



</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>