<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Importar')?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Importar</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">

	<form id="edit_form" name="edit_form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('importsuperproducts/adminhtml_configurable/relations'); ?>" >
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

		<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getStoreConfig('importsuperproducts_options/import/max_file_size'); ?>">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Importação por Relações')?></h4>
        </div> 
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Selecione o arquivo com as relações')?><span class="required">*</span></td>
                    <td class="input-ele"><input name="relations" type="file"></td>
                </tr>
                <tr>
                    <td class="label"><?=$this->__('Selecione o arquivo com os produtos configuráveis')?><span class="required">*</span></td>
                    <td class="input-ele"><input name="configurables" type="file"></td>
                </tr>
            </table>
        <input type="submit" name="submit" value="Importar">
        </fieldset>
	</form>

	<form id="edit_form" name="edit_form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('importsuperproducts/adminhtml_configurable/rules'); ?>" >
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getStoreConfig('importsuperproducts_options/import/max_file_size'); ?>">
		
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Importação por Regra')?></h4>
        </div> 
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Selecione o arquivo com os produtos simples')?><span class="required">*</span></td>
                    <td class="input-ele"><input name="filename" type="file"></td>
                </tr>
                <tr>
                    <td class="label"><?=$this->__('Selecione o delimitador do sku')?><span class="required">*</span></td>
                    <td class="input-ele"><input name="delimiter" type="text"></td>
                </tr>
            </table>
        <input type="submit" name="submit" value="Importar">
        </fieldset>
	</form>

	<form id="edit_form" name="edit_form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('importsuperproducts/adminhtml_category'); ?>" >
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getStoreConfig('importsuperproducts_options/import/max_file_size'); ?>">
		
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Importação de Categorias')?></h4>
        </div> 
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Selecione o arquivo com os produtos simples')?><span class="required">*</span></td>
                    <td class="input-ele"><input name="category" type="file"></td>
                </tr>
            </table>
        <input type="submit" name="submit" value="Importar">
        </fieldset>
	</form>

	<form id="edit_form" name="edit_form" method="post" enctype="multipart/form-data" action="<?php echo $this->getUrl('importsuperproducts/adminhtml_simple'); ?>" >
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		<input type="hidden" name="MAX_FILE_SIZE" value="<?php echo $this->getStoreConfig('importsuperproducts_options/import/max_file_size'); ?>">
		
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Importação de Categorias')?></h4>
        </div> 
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Selecione o arquivo com os produtos simples')?><span class="required">*</span></td>
                    <td class="input-ele"><input name="simple" type="file"></td>
                </tr>
            </table>
        <input type="submit" name="submit" value="Importar">
        </fieldset>
	</form>

</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>